Remove debug parameter in example
debug was removed in #27 but the readme still has it which causes an exception. This will make for a nicer first experience with the library ;)

```
TypeError: unexpected keyword argument 'debug'
```